### PR TITLE
Fix unit test failures

### PR DESCRIPTION
**Pull request by cdzombak**
We have a number of failing unit tests, seemingly caused by https://github.com/NYTimes/NYTPhotoViewer/commit/dc75d987401c4ff6a4b472ec23fb8e756a8a3db8 …

screen shot 2015-10-15 at 14 54 41

Those changes appear to be innocuous—if anything, they look like improvements since now initializing a PhotosVC doesn't immediately load the view too. I plan to:

- go through the offending commit's logic and ensure things are still set up appropriately
- examine each failing test to determine whether we need to load the VC's view before executing the test, or (as in the case of `testCurrentlyDisplayedPhotoIsAccurateAfterSettingInitialPhoto`) whether some PhotosVC implementation logic should be improved.

### CODE REVIEW

**Comment by cdzombak** [comment]
Sigh, I have it down to one test failure. `testUpdateImageForPhotoUpdatesImage` works on iOS 8.4 but crashes on iOS 9:

```
Test Case '-[NYTPhotosViewControllerTests testUpdateImageForPhotoUpdatesImage]' started.
/Users/cdzombak/code/NYTPhotoViewer/Pod/Classes/ios/NYTScalingImageView.m:109: error: -[NYTPhotosViewControllerTests testUpdateImageForPhotoUpdatesImage] : failed: caught "CALayerInvalidGeometry", "CALayer position contains NaN: [nan nan]"
(
	0   CoreFoundation                      0x000000010b64cf65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010b0c6deb objc_exception_throw + 48
	2   CoreFoundation                      0x000000010b64ce9d +[NSException raise:format:] + 205
	3   QuartzCore                          0x000000011192c7e6 _ZN2CA5Layer12set_positionERKNS_4Vec2IdEEb + 152
	4   QuartzCore                          0x000000011192c959 -[CALayer setPosition:] + 44
	5   UIKit                               0x000000010bb6f09a -[UIScrollView setZoomScale:withAnchorPoint:validatingScrollOffset:allowRubberbanding:animated:duration:notifyDelegate:force:] + 1104
	6   UIKit                               0x000000010bb6ec44 -[UIScrollView setZoomScale:withAnchorPoint:validatingScrollOffset:allowRubberbanding:animated:duration:notifyDelegate:] + 42
	7   UIKit                               0x000000010bb6f9f7 -[UIScrollView setZoomScale:animated:] + 1125
	8   Tests                               0x0000000114f636c7 -[NYTScalingImageView updateZoomScale] + 999
	9   Tests                               0x0000000114f63155 -[NYTScalingImageView updateImage:] + 773
	10  Tests                               0x0000000114f59d3d -[NYTPhotoViewController updateImage:] + 109
	11  Tests                               0x0000000114f59c99 -[NYTPhotoViewController photoImageUpdatedWithNotification:] + 345
	12  CoreFoundation                      0x000000010b61987c __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
	13  CoreFoundation                      0x000000010b6195bb _CFXRegistrationPost + 427
	14  CoreFoundation                      0x000000010b619322 ___CFXNotificationPost_block_invoke + 50
	15  CoreFoundation                      0x000000010b65ea72 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1986
	16  CoreFoundation                      0x000000010b514909 _CFXNotificationPost + 633
	17  Foundation                          0x000000010ac56709 -[NSNotificationCenter postNotificationName:object:userInfo:] + 66
	18  Tests                               0x0000000114f5feb7 -[NYTPhotosViewController updateImageForPhoto:] + 119
	19  Tests                               0x0000000114f474a9 -[NYTPhotosViewControllerTests testUpdateImageForPhotoUpdatesImage] + 377
	20  CoreFoundation                      0x000000010b53b85c __invoking___ + 140
	21  CoreFoundation                      0x000000010b53b6ae -[NSInvocation invoke] + 286
	22  XCTest                              0x000000010ab87608 __24-[XCTestCase invokeTest]_block_invoke_2 + 159
	23  XCTest                              0x000000010abb6c90 -[XCTestContext performInScope:] + 184
	24  XCTest                              0x000000010ab87558 -[XCTestCase invokeTest] + 169
	25  XCTest                              0x000000010ab879f3 -[XCTestCase performTest:] + 443
	26  XCTest                              0x000000010ab856b9 -[XCTestSuite performTest:] + 377
	27  XCTest                              0x000000010ab856b9 -[XCTestSuite performTest:] + 377
	28  XCTest                              0x000000010ab856b9 -[XCTestSuite performTest:] + 377
	29  XCTest                              0x000000010ab72ec2 __25-[XCTestDriver _runSuite]_block_invoke + 51
	30  XCTest                              0x000000010ab930cb -[XCTestObservationCenter _observeTestExecutionForBlock:] + 615
	31  XCTest                              0x000000010ab72e0e -[XCTestDriver _runSuite] + 408
	32  XCTest                              0x000000010ab73b6d -[XCTestDriver _checkForTestManager] + 263
	33  XCTest                              0x000000010abb7ff1 _XCTestMain + 628
	34  xctest                              0x000000010aafc25c xctest + 8796
	35  libdyld.dylib                       0x000000010d93e92d start + 1
)
```

so…yeah. Now figuring out what the right approach to fix this test is.

**Comment by cdzombak** [comment]
The iOS 9-only test failure was resolved in https://github.com/NYTimes/NYTPhotoViewer/commit/62b05096ced60183bcce108fb6c0bc16ce80bd7e
